In [1]:
import numpy as np

In [2]:
mylist=[1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
mylist

[1, 2, 3]

In [6]:
myarr=np.array(mylist)

In [7]:
myarr

array([1, 2, 3])

In [8]:
type(myarr)

numpy.ndarray

In [9]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [10]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.ones((5))

array([1., 1., 1., 1., 1.])

In [20]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [21]:
np.linspace(0,10,9)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [22]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [23]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [24]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [25]:
len(np.linspace(0,5,21))

21

In [26]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.random.rand(1)

array([0.12835915])

In [29]:
np.random.rand(5,6)

array([[0.27391741, 0.65663812, 0.07953888, 0.73786995, 0.98447397,
        0.56858538],
       [0.77050651, 0.1667365 , 0.5711693 , 0.67446897, 0.91463443,
        0.54174198],
       [0.38571764, 0.50457812, 0.02063305, 0.94657793, 0.66495032,
        0.21448754],
       [0.6069616 , 0.98177036, 0.77189548, 0.69544436, 0.09947541,
        0.4996821 ],
       [0.64300064, 0.36752545, 0.97774079, 0.86564972, 0.23855825,
        0.04205653]])

In [30]:
np.random.rand(5,2)

array([[0.13439025, 0.49691043],
       [0.40645176, 0.25194137],
       [0.51300746, 0.90867576],
       [0.62669119, 0.75417353],
       [0.79288315, 0.76249862]])

In [31]:
np.random.randn(10)

array([-1.31860024, -0.18809035, -1.06806859, -0.51701105,  1.61871378,
       -0.80912709, -0.4793264 , -0.43765105, -0.43888559,  0.3337963 ])

In [32]:
np.random.randn(2,3)

array([[-0.83506317, -1.1402719 , -0.90075621],
       [-1.84881637,  0.70455498,  1.18501025]])

In [33]:
np.random.randint(0,101,5)

array([69,  9, 22, 81, 65])

In [34]:
np.random.randint(0,101,(4,5))

array([[95, 40, 82, 52, 78],
       [36, 43, 59, 74, 51],
       [ 7, 79, 11,  5,  8],
       [42, 42, 75, 28, 89]])

In [35]:
np.random.randint(0,101,10)

array([90, 12, 45, 38, 19, 76,  4,  3,  0, 31])

In [36]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [37]:
np.random.seed(35)
np.random.rand(4)

array([0.45805495, 0.30834961, 0.23148705, 0.27742455])

In [39]:
arr=np.arange(0,25)

In [40]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
ranarr=np.random.randint(0,101,10)

In [42]:
ranarr

array([73, 15, 55, 33, 63, 64, 11, 11, 56, 72])

In [43]:
ranarr.max()

73

In [44]:
ranarr.min()

11

In [45]:
ranarr.argmax()

0

In [46]:
ranarr.argmin()

6

In [47]:
ranarr.dtype

dtype('int32')

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
arr.shape

(25,)

In [50]:
arr=arr.reshape(5,5)

In [51]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
arr.shape

(5, 5)

In [53]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [54]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])